---
- hosts: localhost
  connection: local
  gather_facts: true
  become: yes

  tasks:
  - include_vars:
      file: /tmp/local_config.json
  - include_role:
      name: bastion
  - include_role:
      name: duo
    when: "duo_enabled"
  - include_role:
      name: dj-wasabi.ossec-agent
    when: "ossec_enabled"
